# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74360dae04b2df016d599aaa35bc00b3ef01f276c1071d028b7577fd9af7896e1699a7ab66dbca0e14ff76e9e8de98ad3965fdaee890fda37daffc5094151444

test:
  secret_key_base: 15b1f5fd3752a978180cb7d05d9329b09d908b456719fc86cdbe2e1bc9721250945ff014e6a04d34a5b67e75b1cb41829ddc2e35106c03e2f63e0a49374900e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
